import { gv } from '../MockGlobals.js';

export const floats = {
  3: `Colonists_Killed_Float`,
  6: `CountdownTimer`,
  7: `TimerCount`,
  8: `CountdownTimer`,
  9: `Node1_Max_Health`,
  10: `Node2_Max_Heath`,
  11: `Node3_Max_Health`,
  12: `Node4_max_Health`,
  13: `Node5_max_Health`,
  14: `Node6_Max_Haelth`,
  15: `Quarian_Countdown`,
  16: `UNC83_Colossus_Timer`,
  18: `Timer_Counter`,
  19: `Bomb_Timer`,
  20: `Best_Score_Scenario_A`,
  21: `Best_Score_Scenario_A`,
  22: `Best_Score_Scenario_B`,
  24: `Selected_Scenario	SFX.DLC_Vegas.test.Selected_Scenario`,
  25: `Scenario_0`,
  26: `Scenario_1`,
  27: `Scenario_2`,
  28: `Scenario_3`,
  29: `Scenario_4`,
  30: `Scenario_5`,
  31: `Scenario_6`,
  32: `Scenario_7`,
  33: `Scenario_8`,
  34: `Scenario_9`,
  35: `Scenario_10`,
  36: `Scenario_11`,
  37: `Scenario_12`,
  38: `Scenario_13`,
  39: `Scenario_14`,
  40: `CargoBay_LastLoadTime`,
  41: `CrewDeck_LastLoadTime`,
  43: `carsonsubplotfloat`,
  44: `carsonsubplotfloat2`,
  45: `StormIntensity`,
};
