import { gv } from '../mockGlobals';

export const ints = {
  1: `Childhood	SFX.Utility.PlayerInfo.Childhood`,
  2: `Reputation	SFX.Utility.PlayerInfo.Reputation`,
  12: `GamingWins	SFX.CH1_Star_Citadel.Gamblatronomatic.GamingWins`,
  13: `Active_World	SFX.Global_Plots.Active_World.Active_World`,
  15: `Romance_Buddy_dialog_count	SFX.Global_Plots.Henchman_Kaidan.Romance_Buddy_dialog_count`,
  16: `Romance_Buddy_dialog_count	SFX.Global_Plots.Henchman_Liara.Romance_Buddy_dialog_count`,
  17: `Romance_Buddy_dialog_count	SFX.Global_Plots.Henchman_Ash.Romance_Buddy_dialog_count`,
  18: `Back_Story_Dialog_Count	Adjust SFX.Global_Plots.Henchman_Garrus.Back_Story_Dialog_Count`,
  21: `Node_Destroyed_Count	SFX.CH2_Feros.Frontier_Lost.Thorian_Nodes.Node_Destroyed_Count`,
  23: `Number_of_Persuades	Adjust SFX.CH1_Star_Citadel.Roleplaying_Plots.Fourth_Estate.Number_of_Persuades`,
  24: `Number_of_Charms	Adjust SFX.CH1_Star_Citadel.Roleplaying_Plots.Fourth_Estate.Number_of_Charms`,
  25: `Number_of_Intimidates	Adjust SFX.CH1_Star_Citadel.Roleplaying_Plots.Fourth_Estate.Number_of_Intimidates`,
  27: `Convinced_Admiral	Adjust SFX.CH1_Star_Citadel.Roleplaying_Plots.RP115_Snap_Inspection.Convinced_Admiral`,
  28: `Steps_Forward	Adjust SFX.CH1_Star_Citadel.Roleplaying_Plots.RP112_I_Remember_Me.Steps_Forward`,
  29: `Talitha_Tension	SFX.CH1_Star_Citadel.Roleplaying_Plots.RP112_I_Remember_Me.Talitha_Tension`,
  31: `Researcher_Killed`,
  32: `HanarResponse	SFX.Global_Plots.Global_Plot_03.HanarResponse`,
  33: `Human_Bar_Conversation	Adjust SFX.CH2_Noveria.ICE20_Conversation_Flags.Human_Bar_Conversation`,
  34: `Salarian_Bar_Conversation	Adjust SFX.CH2_Noveria.ICE20_Conversation_Flags.Salarian_Bar_Conversation`,
  35: `NuriamResponse	SFX.Global_Plots.Global_Plot_03.NuriamResponse`,
  36: `Line	SFX.Utility.Dialog.Select.Line`,
  37: `Making_Garrus_Paragon	Adjust SFX.Global_Plots.Henchman_Garrus.Making_Garrus_Paragon`,
  38: `Making_Garrus_Renegade	Adjust SFX.Global_Plots.Henchman_Garrus.Making_Garrus_Renegade`,
  39: `NumKeepersScanned`,
  40: `Colonist_Killed_Counter`,
  42: `Number_Destroyed`,
  43: `League_Medallion	Adjust SFX.Light_Content_Subplots.Collection_Quest_League_of_One.League_Medallion`,
  44: `Number_of_valves_opened	Adjust SFX.CH2_Feros.Dry_Lands.Number_of_valves_opened`,
  45: `Previous_Active_World	SFX.Global_Plots.Active_World.Previous_Active_World`,
  46: `Renegade_Points	Adjust SFX.Utility.PlayerInfo.Renegade_Points`,
  47: `Paragon_Points	Adjust SFX.Utility.PlayerInfo.Paragon_Points`,
  48: `Light_Metals	Adjust SFX.Light_Content_Subplots.Collection_Quest_Minerals_and_Metals.Light_Metals`,
  50: `Heavy_Metals	Adjust SFX.Light_Content_Subplots.Collection_Quest_Minerals_and_Metals.Iridium`,
  51: `Gasses	Adjust SFX.Light_Content_Subplots.Collection_Quest_Minerals_and_Metals.Titanium`,
  52: `Rare_Earth_Elements	Adjust SFX.Light_Content_Subplots.Collection_Quest_Minerals_and_Metals.Uranium`,
  53: `Prothean_Data_Discs	Adjust SFX.Light_Content_Subplots.Collection_Quest_Prothean_Data_Discs.Prothean_Data_Discs`,
  54: `Asari_Writings	Adjust SFX.Light_Content_Subplots.Collection_Quest_Asari_Writings.Asari_Writings`,
  55: `Turian_Emblems	Adjust SFX.Light_Content_Subplots.Collection_Quest_Turian_Emblems.Turian_Emblems`,
  56: `Captain_ID_Tag	Adjust SFX.Light_Content_Subplots.Collection_Quest_League_of_One.Captain_ID_Tag`,
  57: `Time_Has_Passed_Countdown	SFX.Global_Plots.World_Progress.Time_Has_Passed_Countdown`,
  58: `Environment_Counter`,
  59: `nDemoCharges`,
  62: `Stunt_Points_Found`,
  63: `DUI_Display_String`,
  66: `Current_Location`,
  67: `Last_Clicked_On	SFX.Utility.Henchman.Banter_zones.Last_Clicked_On`,
  68: `In_Zone_ID	SFX.Utility.Henchman.Banter_zones.In_Zone_ID`,
  69: `In_DefaultZone_ID	SFX.Utility.Henchman.Banter_zones.In_DefaultZone_ID`,
  70: `END80_MarauderCount`,
  71: `nCodePosition`,
  72: `END80_ShipHitsTaken`,
  73: `END80_ShipGethDeployed`,
  74: `CurrentMusicState	SFX.Global_Plots.Music.CurrentMusicState`,
  75: `Potential_Fail_Count`,
  76: `Definitely_Failed_Count`,
  77: `nMistakes`,
  78: `nCodePosition`,
  79: `nBarCounter`,
  80: `EquippedWeapon`,
  81: `PlotAddedMaxGrenades	Adjust SFX.Utility.PlayerInfo.PlotAddedMaxGrenades`,
  82: `PlotAddedMaxMedigel	Adjust SFX.Utility.PlayerInfo.PlotAddedMaxMedigel`,
  83: `END80_Ship_ActiveGeth`,
  84: `Count_RiotBarks_Male`,
  85: `Count_RiotBarks_Female`,
  88: `Mission_Counter	Adjust SFX.Global_Plots.Achievements.Mission_Counter`,
  89: `Kaidan_Counter	Adjust SFX.Global_Plots.Achievements.Kaidan_Counter`,
  90: `Ashley_Counter	Adjust SFX.Global_Plots.Achievements.Ashley_Counter`,
  91: `Garrus_Counter	Adjust SFX.Global_Plots.Achievements.Garrus_Counter`,
  92: `Wrex_Counter	Adjust SFX.Global_Plots.Achievements.Wrex_Counter`,
  94: `Liara_Counter	Adjust SFX.Global_Plots.Achievements.Liara_Counter`,
  95: `Tali_Counter	Adjust SFX.Global_Plots.Achievements.Tali_Counter`,
  97: `Node3_EventSpawnCount`,
  98: `Node4_EventSpawnCount`,
  99: `Node6_EventSpawnCount`,
  100: `ScannerRangeGalaxy`,
  101: `Node2_EventSpawnCount`,
  102: `ScannerRangeCluster`,
  103: `ScannerRangeSystem`,
  105: `Current_Galaxy_Viewing`,
  107: `Core_1_Junctions_Destroyed`,
  108: `Core_2_Junctions_Destroyed`,
  109: `Core_3_Junctions_Destroyed`,
  111: `FOVO_Count`,
  114: `Bases_Complete`,
  115: `Kahoku_Corpse_Location`,
  119: `Overlord_1_Counter`,
  120: `Overlord_2_Counter`,
  123: `UNC17_Dropship_Health`,
  124: `UNC17_Spawn_Counter`,
  125: `UNC83_Dropship_Health`,
  126: `UNC83_Spawn_Counter`,
  127: `Flux_TableGroup_TalkCount`,
  128: `Total_Modules_Activated	Adjust SFX.CH2_Noveria.Ice_50_Puzzle.Total_Modules_Activated`,
  129: `Module_Removed	SFX.CH2_Noveria.Ice_50_Puzzle.Module_Removed`,
  130: `SarenFightLocation`,
  131: `Number_of_Torches_Deactivated	Adjust SFX.DLC_UNC.UNC52.Number_of_Torches_Deactivated`,
  134: `Script_CurrentBase`,
  135: `West_Torch_ID`,
  136: `East_Torch_ID`,
  137: `Souch_Torch_ID`,
  138: `Reward_selection	SFX.DLC_UNC.UNC52.Reward_selection`,
  141: `Selected_Scenario_Index	SFX.DLC_Vegas.PRC2.Selected_Scenario_Index`,
  142: `NumFirstPlaceVictories	Adjust SFX.DLC_Vegas.PRC2.NumFirstPlaceVictories`,
  143: `NumTAVictories	Adjust SFX.DLC_Vegas.PRC2.NumTAVictories`,
  144: `TJItemChosen	SFX.DLC_Vegas.PRC2.TJItemChosen`,
  145: `Last_Tried_Scenario_Index`,
  146: `Opponents_Scores_Group_Index`,
  147: `Chosen_Drop	SFX.DLC_Vegas.PRC2AA.Chosen_Drop`,
  148: `Score_Scaling_Level`,
  149: `NumLandingsMade	Adjust SFX.Uncharted.Achievements.NumLandingsMade`,
};
